######################################################################
# Automatically generated by qmake (3.0) ?? 1? 12 14:42:15 2016
######################################################################


qt += core gui widgets

TEMPLATE = app
TARGET = testcmdpro
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
