######################################################################
# Automatically generated by qmake (3.0) ?? 1? 20 21:31:05 2016
######################################################################


QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = TestGoToCell
INCLUDEPATH += .

# Input
HEADERS += ui_GoToCellDialog.h
FORMS += GoToCellDialog.ui
SOURCES += main.cpp


#RC_ICONS = app.ico
